/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BDropdownForm: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BIcon: typeof import('./src/components/stubs/BIcon.vue')['default']
    BIconstack: typeof import('./src/components/stubs/BIconstack.vue')['default']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavItemDropdown: typeof import('bootstrap-vue-next/components/BNav')['BNavItemDropdown']
    BNavText: typeof import('bootstrap-vue-next/components/BNav')['BNavText']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    CivilizationTile: typeof import('./src/components/CivilizationTile.vue')['default']
    GameEnd: typeof import('./src/components/GameEnd.vue')['default']
    GameLog: typeof import('./src/components/GameLog.vue')['default']
    IBiGearFill: typeof import('~icons/bi/gear-fill')['default']
    LeaderTile: typeof import('./src/components/LeaderTile.vue')['default']
    MapSquare: typeof import('./src/components/MapSquare.vue')['default']
    MonumentCard: typeof import('./src/components/MonumentCard.vue')['default']
    MonumentTile: typeof import('./src/components/MonumentTile.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PlayerCard: typeof import('./src/components/PlayerCard.vue')['default']
    PlayerHand: typeof import('./src/components/PlayerHand.vue')['default']
    ProgressCard: typeof import('./src/components/ProgressCard.vue')['default']
    WarBoard: typeof import('./src/components/WarBoard.vue')['default']
  }
}
