name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'joshuahysong'
        reponame: 'RiverGame'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
